# Generated by Django 5.0.6 on 2024-06-08 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='email',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='facebook',
            field=models.CharField(default='#', max_length=220),
        ),
        migrations.AddField(
            model_name='agent',
            name='instagram',
            field=models.CharField(default='#', max_length=220),
        ),
        migrations.AddField(
            model_name='agent',
            name='linkedin',
            field=models.CharField(default='#', max_length=220),
        ),
        migrations.AddField(
            model_name='agent',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='agent',
            name='status',
            field=models.BooleanField(default=True, max_length=220),
        ),
        migrations.AddField(
            model_name='agent',
            name='x',
            field=models.CharField(default='#', max_length=220),
        ),
    ]
