# Generated by Django 5.0.6 on 2024-06-08 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Propertie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='notfound.jpg', upload_to='property')),
                ('title', models.CharField(max_length=100)),
                ('rent', models.IntegerField(default=0)),
                ('area', models.IntegerField(default=0)),
                ('beds', models.IntegerField(default=0)),
                ('baths', models.IntegerField(default=0)),
                ('garages', models.IntegerField(default=0)),
            ],
        ),
    ]
