# Generated by Django 5.0.6 on 2024-06-08 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_agent_email_agent_facebook_agent_instagram_and_more'),
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category_property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='propertie',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='agent.agent'),
        ),
        migrations.AddField(
            model_name='propertie',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='propertie',
            name='view',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='propertie',
            name='category',
            field=models.ManyToManyField(to='property.category_property'),
        ),
    ]
